version: "3.7"

services:
  bbscope:
    build: .
    init: true
    restart: always
    volumes:
      - .:/app/
    command: uvicorn main:app --reload --host=0.0.0.0 --port 8080
    container_name: "phoenixscope"
    ports:
      - 8080:8080
    networks:
      - phoenixscope

networks:
  phoenixscope:
    driver: "bridge"
    name: "phoenixscope"
